### ISSUE TITLE
type error

### ISSUE THREAD

**Issue by vcvishal** [vijaykrishnavanshi/unet-pytorch#2]
TypeError                                 Traceback (most recent call last)
<ipython-input-2-2ee69b88e802> in <module>
      4 with open('Dataset/Lung_CT_Dataset.csv', 'wb') as csv_file:
      5     writer = csv.writer(csv_file)
----> 6     writer.writerow(["filename", "mask"])
      7     for p in os.listdir(IMAGE_DIR):
      8         image_path = os.path.join(IMAGE_DIR, p)

TypeError: a bytes-like object is required, not 'str

**Comment by Nelsi11120** [comment]
try : 
with open('Dataset/Lung_CT_Dataset.csv', 'w') as csv_file:

**Comment by vcvishal** [comment]
thank you it works
